### ISSUE TITLE
Serialize hll state

### ISSUE THREAD

**Issue by copy** [let-def/grenier#3]
I'm using HyperLogLog in a long-running program and would like to save its state to a file, so it would be useful if the module could provide conversion functions to a visible type or make the `Hll.t` type visible.

**Comment by let-def** [comment]
I propose a simple `to_string``/`of_string` pair (you can try with `opam pin add grenier --dev-repo`). Tells me if this suits your needs.

I simplified the representation so that it is no more than a string, this should slightly decrease memory overhead.

I am quite happy with the performance profile but you might have different needs (I use that only for hobby projects :)). Don't hesitate to tell!

**Comment by copy** [comment]
This solution works for me, thanks!

I am also very happy about the performance :-)

**Comment by let-def** [comment]
I pushed an update today.
Estimation was not truncating registers properly, that could decrease the result quality.
So hopefully, it is now closer to the original paper.
